# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rndiy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rndiy

  target 'rndiyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rndiy-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rndiy-tvOS

  target 'rndiy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
